resources:
  - ../base
namePrefix: qwen3-4b-
commonLabels:
  instance: qwen3-4b
configMapGenerator:
  - name: inference-config
    literals:
      - MODEL_ID=qwen3-4b
      - OVERRIDE_MODEL_ID=qwen3-4b
      - DEVICE=cuda
      - MODEL_DTYPE=bfloat16
      - SAE_DTYPE=bfloat16
      - TOKEN_LIMIT=400
      - HOST=0.0.0.0
      - PORT=5002
      - MAX_LOADED_SAES=12
      - SAE_SETS=["transcoder-hp"]
